
POST  http://localhost:8000/blogs  HTTP/1.1
Content-Type: application/json


{
    "title":"4 blog",
    "body":"blog content last",
    "author":"613820bf3106c351e615a83d",
    "likes":7,
    "tags":["technology","React js"]
    
} 


### 

GET http://localhost:8000/Auth/users  HTTP/1.1
Content-Type: application/json

### 

POST http://localhost:8000/Auth/register HTTP/1.1 
Content-Type: application/json 

{
    "username":"mamoaidd22",
    "password":"momo123ddddd",
    "email":"moaidmohamed123d4@gmail.com"
} 


###
POST http://localhost:8000/Auth/login HTTP/1.1 
Content-Type: application/json 

{
    "email":"momo123@gmail.com",
    "password":"momo123456"
    
} 

###

GET http://localhost:8000/blogs  HTTP/1.1
Content-Type: application/json 

###

DELETE http://localhost:8000/blogs/second  blog   
Content-Type: application/json 

###

POST  http://localhost:8000/comments/  HTTP/1.1 
Content-Type: application/json


{
    
    "body":"blog content8",
    "author":"mamoaid",
    "blog":"6133e0d9624c0c403ef4c2a2"
    
}  

### 

GET http://localhost:8000/comments/6133e0d9624c0c403ef4c2a2
Content-Type: application/json 

###

PATCH http://localhost:8000/profile/follow/61340c3a1695ee7af25d2c94     HTTP/1.1 
Content-Type: application/json 

{   
    "followers": [
        "612fd3e0051c46b4113f3570",
        "612fdc41ef634d7dcb7aadc3",
        "61300cfa6c5e7229d9c4757e"
    ]
} 


### 

PATCH http://localhost:8000/profile/follow/61340c3a1695ee7af25d2c94     HTTP/1.1 
Content-Type: application/json 

{
    "followers": "bio111"
} 

GET 